FinalProject/FinalProject/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace FinalProject.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalProject/FinalProject/Controllers/MasonryController.cs
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class MasonryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalProject/FinalProject/Views/About/Index.cshtml
<div id="content" class="site-content">
    <div class="page-header dtable text-center header-transparent pheader-about" style="background-image: url(./images/img/postt.jpg);">
        <div class="dcell">
            <div class="aboutt-imgg">

                <div class="container">
                    <h1 class="page-title">About Us</h1>
                    <ul id="breadcrumbs" class="breadcrumbs none-style">
                        <li><a href="index.html">Home</a></li>
                        <li class="active">About Us</li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <section class="about-company">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12 align-self-center text-center mb-5 mb-lg-0">
                    <div class="about-img">
                        <img src="~/images/img/about us.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 align-self-center">
                    <div class="about-detail">
                        <div class="ot-heading is-dots">
                            <span>[ about company ]</span>
                            <h2 class="main-heading">Best Interior Solutions</h2>
                        </div>
                        <p>The basic philosophy of our studio is to create individual, aesthetically stunning solutions for our customers by lightning-fast development of projects employing unique styles and architecture. Even if you don’t have a ready sketch of what you want – we will help you to get the result you dreamed of.</p>
                        <div class="ot-button">
                            <a asp-action="Index" asp-controller="Masonry" class="octf-btn octf-btn-dark border-hover-dark">View Projects</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <section class="our-philosophy" style="background-image: url(./images/img/123.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 theratio-align-center text-center">
                    <div class="ot-heading is-dots">
                        <span>[ company strategy ]</span>
                        <h2 class="main-heading text-light">Our Philosophy</h2>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 mb-5 mb-xl-0">
                    <div class="support-box">
                        <div class="inner-box">
                            <div class="overlay flex-middle">
                                <div class="inner">
                                    <p>We call our style ‘live minimalism’. Live minimalism is not about a or visual look. It refers to inner feelings, to your true self.</p>
                                </div>
                            </div>
                            <div class="content-box">
                                <div class="icon-title">
                                    <span class="ot-flaticon-brickwall"></span>
                                    <h5>Our Missions</h5>
                                </div>
                                <img src="~/images/img/pantone.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 mb-5 mb-xl-0">
                    <div class="support-box">
                        <div class="inner-box">
                            <div class="overlay flex-middle">
                                <div class="inner">
                                    <p>We call our style ‘live minimalism’. Live minimalism is not about a or visual look. It refers to inner feelings, to your true self.</p>
                                </div>
                            </div>
                            <div class="content-box">
                                <div class="icon-title">
                                    <span class="ot-flaticon-paint"></span>
                                    <h5>Our Vision</h5>
                                </div>
                                <img src="~/images/img/pantone.jpg" class="" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
                    <div class="support-box">
                        <div class="inner-box">
                            <div class="overlay flex-middle">
                                <div class="inner">
                                    <p>We call our style ‘live minimalism’. Live minimalism is not about a or visual look. It refers to inner feelings, to your true self.</p>
                                </div>
                            </div>
                            <div class="content-box">
                                <div class="icon-title">
                                    <span class="ot-flaticon-cube"></span>
                                    <h5>Our Values</h5>
                                </div>
                                <img src="~/images/img/pantone.jpg" class="attachment-full size-full lazyloaded" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>